### ISSUE TITLE
Support for real Regexp

### ISSUE THREAD

**Issue by eightyfive** [futurechan/node_acl-mem-regexp#1]
Hi, nice work.

Is there any particular reason why plain/pure Regexp are not supported?

Looking at:

> Do not include ^ and $. Those will be added for you.

I wonder why this is not possible:

``` js
acl.allow([
    {
        roles:['someRole'], 
        allows:[
            {resources:^\/resource(/[0-9]+)?$, permissions: ['get']},
            {resources:\/[0-9]+$, permissions: ['get']}, // all resources ending with `/:id`
        ]
    }
])
```

Let me know if this is worth my time investigating. I can submit a Pull request to add support for pure Regexp.

Cheers.

**Comment by eightyfive** [comment]
Ok, after reviewing the code a bit, pure RegExps don't seem quite possible (at least easily) because resources are used as `object` keys.

But what about changing [line 72](https://github.com/futurechan/node_acl-mem-regexp/blob/master/lib/memory-backend.js#L72) to:

``` js
var regex = new RegExp(b);
```

That would allow any type of Regular Expressions:

``` js
acl.allow([
    {
        roles:['someRole'], 
        allows:[
            {resources:"^\/resource(/[0-9]+)?$", permissions: ['get']},
            {resources:"\/[0-9]+$", permissions: ['get']}, // all resources ending with `/:id`
        ]
    }
])
```

**Comment by futurechan** [comment]
Couldn't you achieve the same thing with a leading `.+`?

**Comment by eightyfive** [comment]
Yes, you are right.

I guess it's a decision between 1-:

``` js
{resources:"/resource(/[0-9]+)?", permissions: ['get']},
{resources:".+/[0-9]+/.+", permissions: ['get']},
```

And 2-:

``` js
{resources:"^/resource(/[0-9]+)?$", permissions: ['get']},
{resources:"/[0-9]+/", permissions: ['get']},
```

2- Sounds easier to understand & think about to me, because it's plain regexp.

But yeah I'll do that, thanks.

**Comment by eightyfive** [comment]
Dude I don't get what's different between:
https://github.com/OptimalBits/node_acl/blob/master/lib/memory-backend.js

And:
https://github.com/futurechan/node_acl-mem-regexp/blob/master/lib/memory-backend.js

Where's the RegExp magic? ...

**Comment by futurechan** [comment]
Im

**Comment by futurechan** [comment]
It looks like regexp support has been added to the original memory backend. Here's the commit that added it: https://github.com/OptimalBits/node_acl/commit/61d2d7bb9db3bf00a41c2b22f4d7db65ab0afc69 

I haven't used node_acl in over a year. I've been using https://github.com/futurechan/Connect-AccessControl instead.

**Comment by futurechan** [comment]
@eightyfive I would like to get your opinion on https://github.com/futurechan/Connect-AccessControl

**Comment by eightyfive** [comment]
@futurechan It looks nice & simple

Questions:
1. It overlaps with [node_acl](https://github.com/OptimalBits/node_acl) functionalities. What was the initial need?
2. If you refer to [connect](https://github.com/senchalabs/connect) then the name is a bit confusing in my opinion (because your component could be used without the middleware)

**Comment by futurechan** [comment]
1. It was inspired by node_acl. My needs were regexs and simplicity.
2. You're correct. I needed it for an express project I was working on.

Obviously my project doesn't support custom roles per user, so it wouldn't scale to millions of users with custom roles. Also, I feel an in-memory representation of roles is my majority use case. If I need to update those roles in real-time, I will capture an event and update what is stored in memory accordingly.
